apiVersion: v1
data:
  apiToken: ZHQwYzAxLlkzQ0w2TEhQRU9XSDZLTUpMRFBCSUNXUi5STlMyWjVDRkVEUFA0TTVFTzdFRkhTVzRXSFgzR0JBNFI0WEtESjc2UU9WMzRUUlVSMzdPN1VVUDVTNE40UlFG
  dataIngestToken: ZHQwYzAxLjJUM0lTSFlWMkw0NUlPSTI0S0RQRElISS5XV0NLTFhFRkRBUlQ0SEpFS05PWVFGWVMyVzJHREhWQUZMWlFVU1RGTzNJWTJGVU5MWEpFSFlTTVNGUkRJTlRS
kind: Secret
metadata:
  name: cluster-1
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
type: Opaque
---
apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: cluster-1
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://gqm70227.live.dynatrace.com/api
  tokens: cluster-1
  activeGate:
    capabilities:
      - kubernetes-monitoring
    resources:
      requests:
        cpu: 200m
        memory: 6Gi
      limits:
        cpu: 1000m
        memory: 6Gi
    replicas: 1
---
apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: cluster-1-agents
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://gqm70227.live.dynatrace.com/api
  tokens: cluster-1
  oneAgent:
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  activeGate:
    capabilities:
      - routing
      - debugging
    resources:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    replicas: 3
  templates:
    otelCollector:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-otel-collector
        tag: latest
  logMonitoring: {}
  telemetryIngest:
    protocols:
      - jaeger
      - otlp
      - statsd
      - zipkin
    serviceName: telemetry-ingest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
  name: dynatrace-kubernetes-monitoring-sensitive
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - list
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
  name: dynatrace-kubernetes-monitoring-sensitive
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-kubernetes-monitoring-sensitive
subjects:
  - kind: ServiceAccount
    name: dynatrace-activegate
    namespace: dynatrace
